language: node_js
node_js:
- 10
branches:
  only:
  - master
  - /^greenkeeper/.*$/

install:
- npm install

script:
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  on:
    branch: master
  fqdn: where.michaelkohler.info

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - me@michaelkohler.info