name: Test Build

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install Dependencies
      run: npm ci
    - name: Test
      run: npm test
    - name: Build
      run: npm run build
